version: "3"
services: 

    api:
        container_name: api-container
        image: node:16-alpine
        working_dir: /usr/src/clean-node-api 
        restart: always
        command: /bin/sh -c "npm install --only=prod && npm install nodemon -D && npm run debug"
        environment: 
            - MONGO_URL=mongodb://mongo:27017/clean-node-api
        volumes: 
            - ./dist/:/usr/src/clean-node-api/dist/
            - ./package.json:/usr/src/clean-node-api/package.json
        ports: 
            - 5050:5050
            - 9222:9222
        depends_on:
          - mongo   
    
    mongo: 
        container_name: mongo-container
        image: mongo:3
        restart: always
        volumes: 
            - ./dbdata:/data/db
        ports:
            - 27017:27017

# version: "3"

# services:
#   mongo:
#     container_name: mongo-container
#     image: mongo:3
#     restart: always
#     volumes:
#       - ./dbdata:/data/db
#     ports:
#       - 27017:27017


